((cperl-mode . ((cperl-indent-level . 3)
                (cperl-continued-statement-offset . 3)
                (cperl-continued-brace-offset . -3)
                ))
 (perl-mode . ((perl-indent-level . 3)
               )))
